language: python
python:
- '2.7'
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y tree
install:
- pip install -r requirements.txt
script:
- "./runtests.sh"
env:
  secure: Hlu4gDxREXz/Pl/6UWtSxVvl9fwmF4cvKPNOmctkpMkpXXon+X55mPtNOBKhdwp/GhIjGp6F85wMlSgMEPfuLi9XhcTYghu+P+1tbVqt6X+owUfRduo38kdTEH4t/OUOCWNEP6bIO61pr/S4urJo04ScDvCPCzemTsAW6dz/th0=
  global:
  - secure: eLqyEyiI1M1A0j95eSzTgNlSrfYWl+TCoOk10zki9EeQpdT0eC5bQagBJzMXub4u7GAwMeet+v6qsNeEAssWda0eGkyouIQT7KLChEFyCQPXiudRIOpfIMWqNKRV/hi9LlNQQ8xgI/+TM7fzR/T8miQk61xNX2rQ0GXqE30ZQp0=
  - secure: nuUcM+pPbvOYwflxmITOuHl1IqI+zdESqMysP7B24WIsjqY+FwT7uzB/uHSDjlQqoZVUWv2pkeQFyX5guW/h2yofG9B4v5A7svGhtB+mPrQEhUMU53rgP8VBACPHnISQGmr+UxBNNF+PTGRwxxdHRcwC1seg3Ie6MUOhQCkcpeE=
  - secure: HlAQXWzo4Gb1aAES2wfcuNEf/seBGRyUJIppuMejRfsQOTE4i00Vzr28IIPKYNaB+jsehdBC4Z2DgGX22UMLdzsRDm0JQdMp34UckKQQuYeFU+xbAE80CNdHEpxF0c1LwtwJKtuzo5I3ntCm4WOK23Qt4AJw1i9vyuKw0C4hV6o=
