language: python
python:
- '2.7'
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y tree
install:
- pip install -r requirements.txt
script:
- "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY REMOTEDIR=$REMOTEDIR ./runtests.sh"
